apiVersion: v1
kind: Service
metadata:
  name: pvserver-service
  labels:
    app: pvserver
spec:
  type: NodePort
  selector:
    app: pvserver
  ports:
    - protocol: TCP
      port: 11111       # Service が公開するポート
      targetPort: 11111 # POD 内のポート

---
apiVersion: v1
kind: Pod
metadata:
  name: pvserver
  labels:
    app: pvserver
spec:
  initContainers:
  - name: downloader
    image: ubuntu:latest
    env:
    - name: "MINIO_URL"
      value: "https://10.43.210.158"
    - name: "MINIO_ID"
      value: "console"
    - name: "MINIO_SECRET"
      value: "console123"
    - name: "MINIO_BUCKET_NAME"
      value: "test"
    - name: "MINIO_TARGET_DIR"
      value: "single-pipe"
    securityContext:
      runAsUser: 0  
      runAsGroup: 0  
    command: ["/bin/bash","-c"]
    args:
      - |
        apt update
        apt install wget -y
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc alias set bucket $MINIO_URL $MINIO_ID $MINIO_SECRET --insecure
        ./mc cp bucket/$MINIO_BUCKET_NAME/$MINIO_TARGET_DIR /data/ --recursive --insecure
        cp mc /data/
    volumeMounts:
      - name: bucket-files
        mountPath: /data
  containers:
  - name: editor
    image: tyamanakatyamanaka704/pvserver
    securityContext:
    command: ["/bin/bash","-c"]
    args:
      - "pvserver --server-port=11111"
    volumeMounts:
      - name: bucket-files
        mountPath: /data
  volumes:
  - name: bucket-files
    emptyDir: {}