apiVersion: v1
kind: Pod
metadata:
  name: minio-file-editor
spec:
  initContainers:
  - name: downloader
    image: minio/mc
    env:
    - name: "MINIO_URL"
      value: 
    - name: "MINIO_ID"
    - name: "MINIO_SECRET"
    - name: "MINIO_BUCKET_NAME"
    - name: "MINIO_TARGET_DIR"
    command: ["/bin/bash","-c"]
    args:
      - "mc alias set bucket $MINIO_URL $MINIO_ID $MINIO_SECRET"
      - "mc cp $MINIO_BUCKET_NAME$MINIO_TARGET_DIR /data/ --recursive"
    volumeMounts:
      - name: bucket-files
        mountPath: /data
  containers:
  - name: editor
    image: ubuntu:latest
    command: ["/bin/bash","-c"]
    args:
      - "tail -f /dev/null"
    volumeMounts:
      - name: bucket-files
        mountPath: /data
  volumes:
  - name: bucket-files
    emptyDir: {}